using System;

namespace FluentUIComponents
{
    public static class ApiDefinitionConstants
    {
		public const string MSFAccessibleViewDelegate = "_TtP8FluentUI22AccessibleViewDelegate_";
		public const string MSFAccessibleTableViewDelegate = "_TtP8FluentUI27AccessibleTableViewDelegate_";
		public const string MSFActionsCell = "ActionsCell";
		public const string MSFActivityIndicatorCell = "ActivityIndicatorCell";
		public const string MSFActivityIndicatorView = "ActivityIndicatorView";
		public const string MSFAnimationSynchronizer = "AnimationSynchronizerProtocol";
		public const string MSFAnimationSynchronizerProtocol = "AnimationSynchronizerProtocol";
		public const string MSFAvatarData = "AvatarData";
		public const string MSFAvatarView = "AvatarView";
		public const string MSFBadgeField = "BadgeField";
		public const string MSFBadgeViewDelegate = "BadgeViewDelegate";
		public const string MSFBadgeFieldDelegate = "BadgeFieldDelegate";
		public const string MSFBadgeView = "BadgeView";
		public const string MSFBadgeViewDataSource = "BadgeViewDataSource";
		public const string MSFBarButtonItems = "_TtC8FluentUI14BarButtonItems";
		public const string MSFBlurringView = "BlurringView";
		public const string MSFTableViewCell = "TableViewCell";
		public const string MSFBooleanCell = "BooleanCell";
		public const string MSFButton = "Button";
		public const string MSFCalendarConfiguration = "CalendarConfiguration";
		public const string MSFCenteredLabelCell = "CenteredLabelCell";
		public const string MSFColors = "Colors";
		public const string MSFDateTimePicker = "DateTimePicker";
		public const string MSFDateTimePickerDelegate = "DateTimePickerDelegate";
		public const string MSFDimmingView = "DimmingView";
		public const string MSFDotView = "DotView";
		public const string MSFDrawerController = "DrawerController";
		public const string MSFDrawerControllerDelegate = "DrawerControllerDelegate";
		public const string MSFEasyTapButton = "EasyTapButton";
		public const string FluentUIFramework = "_TtC8FluentUI17FluentUIFramework";
		public const string MSFFonts = "Fonts";
		public const string MSFHud = "HUD";
		public const string MSFHudDelegate = "HUDDelegate";
		public const string MSFHudParams = "HUDParams";
		public const string MSFLabel = "Label";
		public const string MSFNavigationBar = "NavigationBar";
		public const string MSFNavigationController = "NavigationController";
		public const string MSFNotificationView = "NotificationView";
		public const string MSFPageCardPresenterController = "PageCardPresenterController";
		public const string MSFPeoplePicker = "PeoplePicker";
		public const string MSFPersonaListViewSearchDirectoryDelegate = "PersonaListViewSearchDirectoryDelegate";
		public const string MSFPeoplePickerDelegate = "PeoplePickerDelegate";
		public const string MSFPersona = "Persona";
		public const string MSFPersonaBadgeViewDataSource = "PersonaBadgeViewDataSource";
		public const string MSFPersonaCell = "PersonaCell";
		public const string MSFPersonaData = "PersonaData";
		public const string MSFPersonaListView = "PersonaListView";
		public const string MSFPillButton = "PillButton";
		public const string MSFPillButtonBar = "PillButtonBar";
		public const string MSFPillButtonBarDelegate = "PillButtonBarDelegate";
		public const string MSFPillButtonBarItem = "PillButtonBarItem";
		public const string MSFPopupMenuController = "PopupMenuController";
		public const string MSFPopupMenuItem = "PopupMenuItem";
		public const string MSFPopupMenuSection = "PopupMenuSection";
		public const string MSFResizingHandleView = "ResizingHandleView";
		public const string MSFScrollView = "ScrollView";
		public const string MSFSearchBar = "SearchBar";
		public const string MSFSearchBarDelegate = "SearchBarDelegate";
		public const string MSFSegmentedControl = "SegmentedControl";
		public const string MSFSeparator = "Separator";
		public const string MSFShimmerAppearance = "ShimmerAppearance";
		public const string MSFShimmerView = "ShimmerView";
		public const string MSFShimmerLinesView = "ShimmerLinesView";
		public const string MSFShimmerLinesViewAppearance = "ShimmerLinesViewAppearance";
		public const string MSFShimmerViewAppearence = "ShimmerViewAppearence";
		public const string MSFTabBarItem = "TabBarItem";
		public const string MSFTabBarView = "TabBarView";
		public const string MSFTabBarViewDelegate = "TabBarViewDelegate";
		public const string MSFTableViewHeaderFooterView = "MSFTableViewHeaderFooterView";
		public const string MSFTableViewHeaderFooterViewDelegate = "MSFTableViewHeaderFooterViewDelegate";
		public const string MSFTooltip = "MSFTooltip";
		public const string MSFTouchForwardingView = "MSFTouchForwardingView";
		public const string MSFTwoLineTitleView = "MSFTwoLineTitleView";
		public const string MSFTwoLineTitleViewDelegate = "MSFTwoLineTitleViewDelegate";
	}
}
